apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: of6su58pf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: of6su58pf-go 
  name: of6su58pf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: of6su58pf-go 
